name: glow_kit
homepage: https://github.com/amityamsi/glow_kit
description: A customizable Flutter glow animation package that adds smooth, animated background glow effects to any widget with multiple shape support and high-performance rendering.
version: 1.0.0
# repository: https://github.com/amityamsi/glow_kit
# issue_tracker: https://github.com/amityamsi/glow_kit/issues

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0

topics:
  - glow-effect
  - custom-widget
  - ripple-effect
  - sound-wave
  - avatar

screenshots:
  - description: "Package Demo"
    path: src/app.gif
